version: '3.9'

services:
  grpc-server:
    build: .
    container_name: grpc-echo-server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: grpcdb
    ports:
      - "50051:50051"

  db:
    image: mysql:8.4
    container_name: grpc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grpcdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  jaeger:                       # ← services の中にインデントして入れる
    image: jaegertracing/all-in-one:1.58
    container_name: grpc-jaeger
    ports:
      - "16686:16686"   # Web UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP（今回は使わない）
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  mysql-data:
