{{- $globalTag := default "latest" .Values.global.imageTag -}}
{{- $svcTag := "" -}}
{{- if and (hasKey .Values "grpcEcho") (hasKey .Values.grpcEcho "image") (hasKey .Values.grpcEcho.image "tag") -}}
{{- $svcTag = .Values.grpcEcho.image.tag -}}
{{- end -}}
{{- $tag := default $globalTag $svcTag -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-echo
spec:
  replicas: {{ .Values.grpcEcho.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: grpc-echo
  template:
    metadata:
      labels:
        app: grpc-echo
    spec:
      containers:
        - name: grpc-echo
          image: "{{ .Values.grpcEcho.image.repository }}:{{ $tag }}"
          imagePullPolicy: {{ .Values.grpcEcho.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 50051
            - containerPort: 9464
          envFrom:
            - configMapRef:
                name: grpc-echo-config
            - secretRef:
                name: grpc-echo-secret

          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 2
            periodSeconds: 5

          {{- with .Values.grpcEcho.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}
