apiVersion: v1
kind: Service
metadata:
  name: http-gateway
  labels:
    app: http-gateway
spec:
  type: {{ .Values.gateway.service.type | default "ClusterIP" }}
  selector:
    app: http-gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port | default 8081 }}
      targetPort: {{ .Values.gateway.service.targetPort | default 8081 }}
