{{- if .Values.gateway.enabled }}

{{- $globalTag := default "latest" .Values.global.imageTag }}
{{- $tag := default $globalTag .Values.gateway.image.tag }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-gateway
  labels:
    app: http-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-gateway
  template:
    metadata:
      labels:
        app: http-gateway
    spec:
      containers:
        - name: http-gateway
          image: "{{ .Values.gateway.image.repository }}:{{ $tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8081
          env:
            - name: GRPC_SERVER_ADDR
              value: "grpc-echo:50051"
            - name: HTTP_LISTEN_ADDR
              value: ":8081"

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5

          resources:
{{ toYaml .Values.gateway.resources | nindent 12 }}

{{- end }}
