{{- if (default false .Values.ingress.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-gateway
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "nginx" }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host | default "grpc-echo.local" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: http-gateway
                port:
                  number: 8081
{{- end }}
