apiVersion: v1
kind: Secret
metadata:
  name: grpc-echo-secret
  labels:
    app.kubernetes.io/name: grpc-echo
    app.kubernetes.io/instance: grpc-echo
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.config.authSecret | quote }}
  DB_USER: {{ .Values.config.db.user | quote }}
  DB_PASSWORD: {{ .Values.config.db.password | quote }}
