image:
  repository: mysql
  tag: "8.4.0"
  pullPolicy: IfNotPresent

auth:
  rootPassword: "root"
  database: "grpcdb"

service:
  port: 3306

persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""
