apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-echo
  template:
    metadata:
      labels:
        app: grpc-echo
    spec:
      containers:
        - name: grpc-echo
          image: grpc-echo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051  # gRPC
            - containerPort: 9464   # metrics (Prometheus)
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"         # mysql.yaml の設定に合わせて root/root
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "grpcdb"
            
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector:4317"

            - name: AUTH_SECRET
              value: "my-dev-secret-key"

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-echo
spec:
  type: ClusterIP
  selector:
    app: grpc-echo
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 9464
      targetPort: 9464
