config:
  authSecret: "my-dev-secret-key"

  db:
    host: "mysql"
    port: 3306
    name: "grpcdb"
    user: "root"
    password: "root"

  otelExporterEndpoint: "otel-collector:4317"

ingress:
  enabled: true
  className: nginx
  host: grpc-echo.local

gateway:
  enabled: true

  image:
    repository: "grpc-http-gateway"
    tag: "latest"         # ← ここを latest に戻す
    pullPolicy: "IfNotPresent"

  service:
    type: "ClusterIP"
    port: 8081
    targetPort: 8081

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

grpcEcho:
  image:
    tag: "latest"         # ← ここも latest に戻す
