global:
  imageTag: "dev"

config:
  authSecret: "my-dev-secret-key"
  db:
    host: "mysql"
    port: 3306
    name: "grpcdb"
    user: "root"
    password: "root"
  otelExporterEndpoint: "otel-collector:4317"

# dev は “差分だけ” でOK（他は values.yaml を継承）
grpcEcho:
  replicaCount: 2

gateway:
  enabled: true

ingress:
  enabled: true
  className: "nginx"
  host: "grpc-echo.local"
