global:
  imageTag: "prod"

config:
  authSecret: "super-secret-in-prod"
  grpcRequestTimeout: "2s"

  db:
    host: "prod-mysql"
    port: 3306
    name: "grpcdb"
    user: "appuser"
    password: "prod-db-password"
  otelExporterEndpoint: "otel-collector:4317"

# prod も “差分だけ”
grpcEcho:
  replicaCount: 2

gateway:
  enabled: true

ingress:
  enabled: true
  className: "nginx"
  host: "grpc-echo.local"
