apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../otel-collector.yaml
  - ../tempo.yaml
  - ../prometheus.yaml
  - ../grafana.yaml

commonLabels:
  app.kubernetes.io/part-of: grpc-echo
  app.kubernetes.io/component: observability
